
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: firmware
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.uf2"
